- name: Add Local Researcher
  user:
    name: "{{ item.name }}"
    shell: "/bin/bash"
    password: "{{ item.user_password }}"
  with_items: "{{researchers}}"
  when: researchers is defined

- name: Create SSH Directory
  file: dest=/home/{{ item.name }}/.ssh owner={{ item.name }} group={{ item.name }} mode=750 state=directory
  with_items: "{{researchers}}"
  when: researchers is defined

#- name: Setup Researcher Public Keys
#  authorized_key:
#    user: "{{ item }}"
#    key: "{{ lookup('file', './roles/add-researcher/files/' + item + '-id_rsa.pub') }}"
#  with_items: "{{researchers}}"
#  when: researchers is defined
