- name: Install Base Packages
  yum: name={{ item }} state=present
  with_items:
   - tmux
   - vim-common
   - vim-enhanced
   - ntp
   - ntpdate
   - epel-release
   - net-tools
   - libsemanage-python
   - libselinux-python

- name: Update Cache and All Packages
  yum: name=* state=latest

- name: Enable NTP on Startup
  service: name=ntpd state=started enabled=yes

- name: Disable password access through SSH
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" state=present line="PasswordAuthentication no"
  notify: restart sshd

- name: Add Admin Local Admin Users
  user: name={{ item }} groups=wheel shell=/bin/bash
  with_items: "{{local_admins}}"

- name: Create SSH Directory
  file: dest=/home/{{ item }}/.ssh owner={{ item }} group={{ item }} mode=750 state=directory
  with_items: "{{local_admins}}"

- name: Setup Public Keys
  copy: src={{ item }}-id_rsa.pub dest=/home/{{ item }}/.ssh/authorized_keys owner={{ item }} group={{ item }} mode=750
  with_items: "{{local_admins}}"

- name: Add Local Data Users
  user: name={{ item }} shell=/bin/bash
  with_items: "{{data_users}}"

- name: Create SSH Directory
  file: dest=/home/{{ item }}/.ssh owner={{ item }} group={{ item }} mode=750 state=directory
  with_items: "{{data_users}}"

- name: Setup Public Keys
  copy: src={{ item }}-id_rsa.pub dest=/home/{{ item }}/.ssh/authorized_keys owner={{ item }} group={{ item }} mode=750
  with_items: "{{data_users}}"

- name: Copy ntp.conf file into place
  copy: src=ntp.conf dest=/etc/ntp.conf owner=root group=root mode=644 backup=yes
  notify: restart ntpd

- name: Check Current Timezone Symlink
  stat: path=/etc/localtime
  register: timestat

- name: Set Timezone to UTC
  command: timedatectl set-timezone "{{ timezone }}"
  when: timestat.stat.lnk_source != '/usr/share/zoneinfo/UTC'
  notify: restart ntpd

- name: Setup Sudoers
  copy: src=sudoers dest=/etc/sudoers owner=root group=root mode=440

- name: Copy Hosts Allow File Into Place to Allow SSH only by default
  copy: src=hosts.allow dest=/etc/hosts.allow owner=root group=root mode=644 backup=yes

- name: Copy Hosts Deny File Into Place to Disallow all services by default
  copy: src=hosts.deny dest=/etc/hosts.deny owner=root group=root mode=644 backup=yes

- name: Disable TCP Forwarding
  lineinfile: dest=/etc/ssh/sshd_config line="AllowTcpForwarding no"
  notify: restart sshd
