
- name: Install MATE
  yum: name="@^MATE Desktop" state=present

- name: Install desktop tools
  yum: name={{ item }} state=present
  with_items:
    - libreoffice
    - libreoffice-postgresql

- name: Copy the desktop file
  template:
    src: desktop.j2
    dest: "/etc/sysconfig/desktop"

- name: Install TigerVNC
  yum: name={{ item }} state=present
  with_items:
   - tigervnc-server

- name: Copy default password file
  template:
    src: password.j2
    dest: /tmp/passwd.{{ item.name }}
  with_items: "{{ researchers }}"

- name: Set vnc password
  shell: "sudo -u {{ item.name }} -i vncpasswd < /tmp/passwd.{{ item.name }}"
  with_items: "{{ researchers }}"

- name: Delete vnc password file
  shell: "rm -rf /tmp/passwd.{{ item.name }}"
  with_items: "{{ researchers }}"

- name: Register a vncserver service
  template:
    src: vncserver.j2
    dest: "/etc/systemd/system/vncserver-{{ item.name }}@:{{ item.xdisplay }}.service"
    owner: root
    group: root
  with_items: "{{ researchers }}"
  register: vnc_service

- name: Restart mate-session if it's not running
  cron:
    name: "Restart vnc if !gnome-session for {{ item.name }}"
    job: "if ! pgrep -u {{ item.name }} -x 'mate-session' > /dev/null; then systemctl restart vncserver-{{ item.name }}\\@\\:{{ item.xdisplay }}; fi"
  with_items: "{{ researchers }}"

- name: Add vncserver to boot
  command: "systemctl enable vncserver-{{ item.name }}@:{{ item.xdisplay }}.service"
  with_items: "{{ researchers }}"

- name: Make sure firewall is running
  service:
    name: firewalld
    state: started

- name: "Open port 5900-5910"
  firewalld:
    zone: public
    port: 5900-5910/tcp
    permanent: true
    state: enabled

- name: Copy rstudio RPM
  copy:
    src: rstudio.rpm
    dest: /tmp/rstudio.rpm

- name: Install rstudio
  yum: name=/tmp/rstudio.rpm state=present
