---

- include: analysis-deps.yml

- name: create notebooks directory
  file:
    state: directory
    dest: /home/{{ item.name }}/notebooks
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  with_items: "{{ researchers }}"

- name: create default notebook profile
  sudo: yes
  file:
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    state: directory
    recurse: yes
    dest: /home/{{ item.name }}/.ipython/profile_default
  with_items: "{{ researchers }}"

- name: configure default notebook
  sudo: yes
  template:
    owner: "{{item.name}}"
    group: "{{item.name}}"
    src: ipynb_conf.py.j2
    dest: /home/{{item.name}}/.ipython/profile_default/ipython_notebook_config.py
  with_items: "{{ researchers }}"
#  notify: restart ipython-notebook
