---
- name: install python setup tools (easy_install)
  apt:
    pkg: python-setuptools
    state: present

- name: install pip
  sudo: yes
  easy_install:
    name: pip

- include: analysis-deps.yml

- name: create notebooks directory
  file:
    state: directory
    dest: "/home/{{researcher}}/notebooks"
    owner: "{{researcher}}"
    group: "{{researcher}}"

- name: create default notebook profile
  sudo: yes
  file:
    owner: "{{researcher}}"
    group: "{{researcher}}"
    state: directory
    recurse: yes
    dest: /home/{{researcher}}/.ipython/profile_default

- name: configure default notebook
  sudo: yes
  template:
    owner: "{{researcher}}"
    group: "{{researcher}}"
    src: ipynb_conf.py.j2
    dest: /home/{{researcher}}/.ipython/profile_default/ipython_notebook_config.py
  notify: restart ipython-notebook

- name: Configure upstart script
  template:
    src: upstart.conf.j2
    dest: /etc/init/ipython-notebook.conf
  notify: restart ipython-notebook

- include: nbextensions.yml

- name: Start application
  service: name=ipython-notebook state=started
