- name: Install Base Packages
  yum: name={{ item }} state=present
  with_items:
   - qemu-kvm 
   - qemu-img 
   - virt-manager 
   - libvirt 
   - libvirt-python
   - libvirt-client
   - virt-install
   - virt-viewer

- name: Disable password access through SSH
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" state=present line="PermitRootLogin yes"
  notify: restart sshd
