- name: Install SciPy Packages
  yum: name={{ item }} state=present
  with_items:
    - numpy
    - scipy
    - python-matplotlib
    - ipython
    - python-pandas
    - sympy
    - python-nose
    - atlas-devel
    - postgresql
    - postgresql-devel

- name: Install Pip
  easy_install: name=pip state=present

- name: Install Python packages
  pip: name={{ item }}
  with_items:
    - nltk
    - scikit-learn
    - scipy
    - numpy
    - gensim
    - pandas
    - maplotlib
    - seaborn
    - statsmodels
    - spacy
    - tensorflow
    - ipython

- name: Install Pre-reqs for PostgreSQL Python Connector
  yum: name="@Development Tools" state=present

- name: Install PostgreSQL Python Connector
  pip: name=psycopg2

- name: Uninstall Pre-reqs for PostgreSQL Python Connector
  yum: name="@Development Tools" state=removed

- name: Install R
  yum: name="R" state=present

- name: Install R packages
  command: /usr/bin/Rscript --slave --no-save --no-restore-history -e "if (! ('{{item}}' %in% installed.packages()[,'Package'])) install.packages(pkgs='{{item}}', repos=c('http://www.freestatistics.org/cran/'))"
  with_items:
    - rjson
    - RPostgreSQL
    - data.table
    - ggplot2
    - lfe
    - lubridate
    - zoo
    - ggthemes
    - RColorBrewer
    - scales
    - stringi
    - sp
    - maps
    - maptools
    - broom
    - raster
    - geosphere
    - rgdal
    - rgeos
    - readr
    - dplyr
    - GISTools

- name: Create GloVe directory
  file: path=/opt/glove state=directory mode=0777

- name: Download GloVe vectors
  get_url:
    url: {{ item }}
    dest: /opt/glove
    mode: 0777
  with_items:
    - http://nlp.stanford.edu/data/glove.6B.zip
    - http://nlp.stanford.edu/data/glove.42B.300d.zip
    - http://nlp.stanford.edu/data/glove.840B.300d.zip
    - http://nlp.stanford.edu/data/glove.twitter.27B.zip
