- name: Install SciPy Packages
  yum: name={{ item }} state=present
  with_items:
    - numpy
    - scipy
    - python-matplotlib
    - ipython
    - python-pandas
    - sympy
    - python-nose
    - atlas-devel
    - postgresql
    - postgresql-devel

- name: Install Pip
  easy_install: name=pip state=present

- name: Install NLTK
  pip: name=nltk

- name: Install SciKit-Learn
  pip: name=scikit-learn

- name: Install Pre-reqs for PostgreSQL Python Connector
  yum: name="@Development Tools" state=present

- name: Install PostgreSQL Python Connector
  pip: name=psycopg2

- name: Uninstall Pre-reqs for PostgreSQL Python Connector
  yum: name="@Development Tools" state=removed

