---
- hosts: berkeley-data-node
  become: true
  gather_facts: yes
  vars:
    server_name: berkeley-data-node
    researchers:
      - name: "adrian"
        user_password: "{{ lookup('password', 'credentials/berkeley.adrian length=15 encrypt=sha512_crypt') }}"
        vnc_password: "{{ lookup('password', 'credentials/berkeley.adrian length=15') }}"
        xdisplay: 0
      - name: "orianna"
        user_password: "{{ lookup('password', 'credentials/berkeley.orianna length=15 encrypt=sha512_crypt') }}"
        vnc_password: "{{ lookup('password', 'credentials/berkeley.orianna length=15') }}"
        xdisplay: 1
  roles:
    - base-os
    - data-node
    - hostname
    - update-all
    - add-researcher
    - desktop
    - jupyter
  tasks:
  - name: Install Git
    yum: name=git state=present
