---
- hosts: brain-data-node
  become: true
  gather_facts: yes
  vars:
    server_name: brain-data-node
    researchers:
      - name: "rebekah"
        user_password: "{{ lookup('password', 'credentials/brain.rebekah length=15 encrypt=sha512_crypt') }}"
        vnc_password: "{{ lookup('password', 'credentials/brain.rebekah length=15') }}"
        xdisplay: 0
      - name: "joe"
        user_password: "{{ lookup('password', 'credentials/brain.joe length=15 encrypt=sha512_crypt') }}"
        vnc_password: "{{ lookup('password', 'credentials/brain.joe length=15') }}"
        xdisplay: 1
  roles:
    - base-os
    - data-node
    - hostname
    - update-all
    - add-researcher
    - desktop
    - jupyter
  tasks:
  - name: Install Git
    yum: name=git state=present
