---
- hosts: brain-data-node
  become: true
  gather_facts: yes
  vars:
    server_name: brain-data-node
  roles:
    - base-os
    - data-node
    - hostname
    - update-all
  tasks:
  - name: Install Git
    yum: name=git state=present
