---
- hosts: cornell-data-node
  become: true
  gather_facts: yes
  vars:
    server_name: cornell-data-node
    researchers:
      - name: "cristian"
        user_password: "{{ lookup('password', 'credentials/cornell.cristian length=15 encrypt=sha512_crypt') }}"
        vnc_password: "{{ lookup('password', 'credentials/cornell.cristian length=15') }}"
        xdisplay: 0
      - name: "justine"
        user_password: "{{ lookup('password', 'credentials/cornell.justine length=15 encrypt=sha512_crypt') }}"
        vnc_password: "{{ lookup('password', 'credentials/cornell.justine length=15') }}"
        xdisplay: 1
  roles:
    - base-os
    - data-node
    - hostname
    - update-all
    - add-researcher
    - desktop
    - jupyter
  tasks:
  - name: Install Git
    yum: name=git state=present
