---
- hosts: northwestern-data-node
  become: true
  gather_facts: yes
  vars:
    server_name: northwestern-data-node
    researchers:
      - name: "james"
        user_password: "{{ lookup('password', 'credentials/northwestern.james length=15 encrypt=sha512_crypt') }}"
        vnc_password: "{{ lookup('password', 'credentials/northwestern.james length=15') }}"
        xdisplay: 0
  roles:
    - base-os
    - data-node
    - hostname
    - update-all
    - add-researcher
    - desktop
    - jupyter
  tasks:
  - name: Install Git
    yum: name=git state=present
