---
- hosts: stanford-ess-data-node
  become: true
  gather_facts: yes
  vars:
    server_name: stanford-ess-data-node
    researchers:
      - name: "marshall"
        user_password: "{{ lookup('password', 'credentials/stanford-ess.marshall length=15 encrypt=sha512_crypt') }}"
        vnc_password: "{{ lookup('password', 'credentials/stanford-ess.marshall length=15') }}"
        xdisplay: 0
      - name: "patrick"
        user_password: "{{ lookup('password', 'credentials/stanford-ess.patrick length=15 encrypt=sha512_crypt') }}"
        vnc_password: "{{ lookup('password', 'credentials/stanford-ess.patrick length=15') }}"
        xdisplay: 1
  roles:
    - base-os
    - data-node
    - hostname
    - update-all
    - add-researcher
    - desktop
    - jupyter
  tasks:
  - name: Install Git
    yum: name=git state=present
