---
- hosts: stanford-cs-data-node
  become: true
  gather_facts: yes
  vars:
    server_name: stanford-cs-data-node
    researchers:
      - name: "jure"
        user_password: "{{ lookup('password', 'credentials/stanford-cs.jure length=15 encrypt=sha512_crypt') }}"
        vnc_password: "{{ lookup('password', 'credentials/stanford-cs.jure length=15') }}"
        xdisplay: 0
      - name: "tim"
        user_password: "{{ lookup('password', 'credentials/stanford-cs.tim length=15 encrypt=sha512_crypt') }}"
        vnc_password: "{{ lookup('password', 'credentials/stanford-cs.tim length=15') }}"
        xdisplay: 1
      - name: "reid"
        user_password: "{{ lookup('password', 'credentials/stanford-cs.reid length=15 encrypt=sha512_crypt') }}"
        vnc_password: "{{ lookup('password', 'credentials/stanford-cs.reid length=15') }}"
        xdisplay: 2
  roles:
    - base-os
    - data-node
    - hostname
    - update-all
    - add-researcher
    - desktop
    - jupyter
  tasks:
  - name: Install Git
    yum: name=git state=present
