---
- hosts: ut-austin-data-node
  become: true
  gather_facts: yes
  vars:
    server_name: ut-austin-data-node
    researcher: hannah
    user_password: "{{ lookup('password', 'credentials/utaustin length=15 encrypt=sha512_crypt') }}"
    vnc_password: "{{ lookup('password', 'credentials/utaustin length=15') }}"
    vnc_users:
      - name: hannah
        xdisplay: 1
  roles:
    - base-os
    - data-node
    - hostname
    - add-researcher
    - desktop
    - jupyter
  tasks:
  - name: Install Git
    yum: name=git state=present
