---
- hosts: ut-austin-data-node
  become: true
  gather_facts: yes
  vars:
    server_name: ut-austin-data-node
    researcher: hannah
  roles:
    - base-os
    - data-node
    - hostname
    - add-researcher
  tasks:
  - name: Install Git
    yum: name=git state=present
